#https://medium.com/@paramsingh_66174/ci-cd-pipeline-for-react-native-apps-98246237e29d
name: "Android Build"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install modules
        run: bun install

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android ${{inputs.environment == 'release' && 'Release' || 'Debug'}}
        run: |
          cd android && ./gradlew assemble${{inputs.environment == 'release' && 'Release' || 'Debug'}} --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "android/app/build/outputs/apk/release/app-release.apk"
