#https://medium.com/@paramsingh_66174/ci-cd-pipeline-for-react-native-apps-98246237e29d
name: "Android Build"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: "debug"
  push:
    tags:
      - 'v*'
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install modules
        run: bun install

      - name: Extract key
        if: ${{ inputs.environment == 'release' || github.ref }}
        run: |
          echo "${{ secrets.ANLIBRN_UPLOAD_STORE_FILE_CONTENT }}" | base64 --decode > ~/${{ secrets.ANLIBRN_UPLOAD_STORE_FILE }}.keystore
          cat <<EOF > ~/gradle.properties
          ANLIBRN_UPLOAD_STORE_FILE=~/${{ secrets.ANLIBRN_UPLOAD_STORE_FILE }}
          ANLIBRN_UPLOAD_KEY_ALIAS=${{ secrets.ANLIBRN_UPLOAD_KEY_ALIAS }}
          ANLIBRN_UPLOAD_STORE_PASSWORD=${{ secrets.ANLIBRN_UPLOAD_STORE_PASSWORD }}
          ANLIBRN_UPLOAD_KEY_PASSWORD=${{ secrets.ANLIBRN_UPLOAD_KEY_PASSWORD }}
          EOF

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew

      - name: Build android ${{inputs.environment == 'release' || github.ref && 'Release' || 'Debug'}}
        run: |
          cd android && ./gradlew assemble${{inputs.environment == 'release' || github.ref && 'Release' || 'Debug'}} --no-daemon

      - name: Upload release artifact
        if: ${{ inputs.environment == 'release' || github.ref }}
        uses: actions/upload-artifact@v4
        with:
          path: "android/app/build/outputs/apk/release/app-release.apk"

      - name: Upload debug artifact
        if: ${{ inputs.environment != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          path: "android/app/build/outputs/apk/debug/app-debug.apk"

      - name: Create Release
        id: create_release
        if: ${{ inputs.environment == 'release' || github.ref }}
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true
